services:
  # Simple Elasticsearch without SSL for development
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -v '\"status\":\"red\"'"]
      interval: 10s
      timeout: 10s
      retries: 120

  # Simple Kibana without SSL
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.15.2
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - kibanadata:/usr/share/kibana/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 10s
      timeout: 10s
      retries: 120

  # Simple APM Server without SSL
  apm-server:
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/apm/apm-server:8.15.2
    ports:
      - 8200:8200
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.rum.allow_origins=["*"]
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=http://kibana:5601
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
        -E setup.template.settings.index.number_of_replicas=0
        -E setup.dashboards.enabled=true
        -E setup.template.enabled=true
        -E setup.kibana.dashboards.enabled=true
        -E logging.level=info
        -E apm-server.data_streams.enabled=true
        -E apm-server.auth.anonymous.enabled=true
        -E apm-server.auth.anonymous.allow_service=["*"]
        -E apm-server.auth.anonymous.allow_agent=["*"]
        -E setup.ilm.enabled=auto
        -E setup.template.pattern=apm-*
        -E setup.template.name=apm
        -E setup.kibana.username=""
        -E setup.kibana.password=""
    healthcheck:
      test: ["CMD-SHELL", "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/"]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local

networks:
  elastic:
    driver: bridge